# Site settings
title: "People Think"
description: "A blog about politics, opinions, and insights into current events."
keywords: "politics, blog, news, opinions, insights"
#url: "https://www.youtube.com/@47thcapsule"  # Replace with your GitHub Pages URL or your site URL
baseurl: "/"  # Keep it as "/" for root directory or set for subdirectory like "/your-repository-name"
theme: jekyll-theme-slate  # Optional: Set a Jekyll theme, or you can leave it out if using custom styles

# Markdown processing settings
markdown: kramdown
highlighter: rouge

# Permalinks setting
permalink: pretty  # Uses pretty URLs like `/about/` instead of `/about.html`

# Navigation menu links
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "News"
    url: "/news"
  - title: "Trump Info"
    url: "/trump-info"
    submenu:
      - title: "Biography"
        url: "/biography"
      - title: "Trump Policies"
        url: "/trump-policies"
  - title: "From Business to Politics"
    url: "/From Business to Politics: The Lasting Impact of Donald Trump's Presidency.md"

# Author information (optional)
author:
  name: "hasnainmorani"
  email: "hasnainmorani700@gmail.com"

# Social media links (optional)
social:
  twitter: "https://twitter.com/yourusername"
  linkedin: "https://linkedin.com/in/yourusername"
  github: "https://github.com/your-username"
  youtube: "https://www.youtube.com/@47thcapsule"
# Plugins (optional)
plugins:
  - jekyll-seo-tag  # For SEO optimization
  - jekyll-feed     # To generate RSS feeds

# Build settings
markdown_ext: "md"
exclude:
  - README.md   # You can exclude files from being processed by Jekyll
  - LICENSE.md

# Google Analytics (optional)
google_analytics: "UA-XXXXXXX-X"

# Authorizing and Generating Assets
assets:
  css_dir: "/assets/styles.css"
  js_dir: "/assets/scripts.js"
  images_dir: "/assets/images"
